# -*- coding: utf-8 -*-
# Hand-written, easy-German (B1-level) definitions for the app's own core
# vocabulary. Each entry: lemma -> (Wortart, simple meaning, simple example).
# forms maps every inflected surface form that actually appears in the app's
# content to its lemma, so a click on "läuft" resolves to "laufen", etc.

ENTRIES = {
 # --- Zeit ---
 "Jahr": ("Substantiv", "Ein Zeitabschnitt von zwölf Monaten.", "Nächstes Jahr fahre ich nach Italien."),
 "Woche": ("Substantiv", "Ein Zeitabschnitt von sieben Tagen.", "Ich arbeite fünf Tage in der Woche."),
 "Tag": ("Substantiv", "Ein Zeitabschnitt von 24 Stunden.", "Heute ist ein schöner Tag."),
 "Monat": ("Substantiv", "Ein Teil des Jahres, meistens 30 oder 31 Tage.", "Der Dezember ist der letzte Monat des Jahres."),
 "Abend": ("Substantiv", "Die Zeit, wenn es dunkel wird, vor der Nacht.", "Am Abend sehe ich gern fern."),
 "Wochenende": ("Substantiv", "Samstag und Sonntag.", "Am Wochenende schlafe ich lange."),
 "heute": ("Adverb", "An diesem Tag, jetzt.", "Heute ist Montag."),
 "damals": ("Adverb", "Zu einer Zeit in der Vergangenheit.", "Damals gab es noch kein Internet."),
 "letzte": ("Adjektiv", "Ganz am Ende einer Reihe; zuletzt.", "Das war die letzte Frage."),
 "nächste": ("Adjektiv", "Was direkt danach kommt.", "Wir sehen uns nächste Woche."),
 "inzwischen": ("Adverb", "In der Zeit dazwischen; mittlerweile.", "Inzwischen ist er erwachsen."),
 "plötzlich": ("Adverb", "Sehr schnell und ohne Vorwarnung.", "Plötzlich fing es an zu regnen."),
 "endlich": ("Adverb", "Nach langer Zeit, zum Schluss.", "Endlich ist der Sommer da."),
 "früher": ("Adverb", "In der Vergangenheit, vor langer Zeit.", "Früher gab es hier keine Häuser."),
 "erst": ("Adverb", "Nicht früher als; gerade eben.", "Ich bin erst vor einer Stunde angekommen."),

 # --- Familie ---
 "Familie": ("Substantiv", "Eltern, Kinder und andere Verwandte zusammen.", "Meine Familie ist sehr groß."),
 "Vater": ("Substantiv", "Der männliche Elternteil.", "Mein Vater arbeitet in einer Bank."),
 "Mutter": ("Substantiv", "Der weibliche Elternteil.", "Meine Mutter kocht sehr gut."),
 "Großvater": ("Substantiv", "Der Vater der Mutter oder des Vaters.", "Mein Großvater erzählt gern alte Geschichten."),
 "Großmutter": ("Substantiv", "Die Mutter der Mutter oder des Vaters.", "Meine Großmutter wohnt auf dem Land."),
 "Bruder": ("Substantiv", "Ein männliches Geschwisterkind.", "Mein Bruder ist zwei Jahre älter als ich."),
 "Schwester": ("Substantiv", "Ein weibliches Geschwisterkind.", "Meine Schwester studiert in Berlin."),
 "Kind": ("Substantiv", "Ein junger Mensch, der noch nicht erwachsen ist.", "Das Kind spielt im Garten."),
 "Eltern": ("Substantiv", "Vater und Mutter zusammen.", "Meine Eltern wohnen in München."),
 "Ehepaar": ("Substantiv", "Zwei Menschen, die miteinander verheiratet sind.", "Das ältere Ehepaar hat das Haus verkauft."),

 # --- Menschen/Rollen ---
 "Mensch": ("Substantiv", "Eine Person; ein Lebewesen wie du und ich.", "Jeder Mensch macht manchmal Fehler."),
 "Frau": ("Substantiv", "Eine erwachsene weibliche Person.", "Die Frau wartet an der Bushaltestelle."),
 "Mann": ("Substantiv", "Eine erwachsene männliche Person.", "Der Mann trägt einen grünen Mantel."),
 "Angestellte": ("Substantiv", "Eine Person, die für eine Firma arbeitet.", "Die Angestellte hilft mir sehr freundlich."),
 "Experte": ("Substantiv", "Eine Person, die sehr viel über ein Thema weiß.", "Der Experte erklärt das Problem genau."),
 "Forscher": ("Substantiv", "Eine Person, die wissenschaftlich untersucht, wie etwas funktioniert.", "Die Forscher beobachten die Tiere seit Jahren."),
 "Nachbarin": ("Substantiv", "Eine Frau, die direkt neben dir oder in deiner Nähe wohnt.", "Meine Nachbarin ist sehr hilfsbereit."),
 "Mitarbeiter": ("Substantiv", "Eine Person, die zusammen mit anderen in einer Firma arbeitet.", "Alle Mitarbeiter waren mit dem neuen Modell zufrieden."),
 "Chef": ("Substantiv", "Die Person, die in einer Firma die Entscheidungen trifft.", "Mein Chef ist heute nicht im Büro."),
 "Rentnerin": ("Substantiv", "Eine Frau, die nicht mehr arbeitet, weil sie alt genug ist.", "Die Rentnerin räumt ihren Dachboden auf."),

 # --- Orte ---
 "Stadt": ("Substantiv", "Ein großer Ort, in dem viele Menschen wohnen.", "Berlin ist eine sehr große Stadt."),
 "Dorf": ("Substantiv", "Ein kleiner Ort auf dem Land.", "In dem Dorf kennt fast jeder jeden."),
 "Bank": ("Substantiv", "Eine Firma, bei der man Geld einzahlt, abhebt oder aufbewahrt.", "Sie geht zur Bank, um Geld abzuheben."),
 "Bahnhof": ("Substantiv", "Der Ort, an dem Züge halten und Menschen einsteigen.", "Der Bahnhof ist zehn Minuten zu Fuß entfernt."),
 "Insel": ("Substantiv", "Ein Stück Land, das ganz von Wasser umgeben ist.", "Wir verbringen den Urlaub auf einer Insel."),
 "Küste": ("Substantiv", "Der Rand des Landes direkt am Meer.", "Viele Touristen besuchen die Küste im Sommer."),
 "Dachboden": ("Substantiv", "Der Raum ganz oben im Haus, direkt unter dem Dach.", "Alte Sachen liegen oft auf dem Dachboden."),
 "Ferienhaus": ("Substantiv", "Ein Haus, in dem man nur im Urlaub wohnt.", "Wir mieten jedes Jahr das gleiche Ferienhaus."),

 # --- Kernverben ---
 "arbeiten": ("Verb", "Eine Tätigkeit ausführen, oft gegen Geld.", "Ich arbeite von Montag bis Freitag."),
 "finden": ("Verb", "Etwas entdecken, das man gesucht hat, oder eine Meinung zu etwas haben.", "Ich finde diesen Film sehr interessant."),
 "bringen": ("Verb", "Etwas zu einem Ort oder zu einer Person tragen.", "Kannst du mir bitte ein Glas Wasser bringen?"),
 "bleiben": ("Verb", "An einem Ort sein und nicht weggehen.", "Wir bleiben heute zu Hause."),
 "brauchen": ("Verb", "Etwas nötig haben.", "Ich brauche mehr Zeit für diese Aufgabe."),
 "glauben": ("Verb", "Denken, dass etwas wahr ist, ohne es sicher zu wissen.", "Ich glaube, dass es morgen regnet."),
 "erinnern": ("Verb", "An etwas aus der Vergangenheit denken, es nicht vergessen haben.", "Sie erinnert sich gut an ihre Kindheit."),
 "erzählen": ("Verb", "Anderen Menschen von etwas berichten, meistens mit Worten.", "Er erzählt gern Geschichten von früher."),
 "beschließen": ("Verb", "Eine feste Entscheidung treffen.", "Sie beschließen, gemeinsam zu verreisen."),
 "versuchen": ("Verb", "Etwas probieren, ohne sicher zu sein, ob es klappt.", "Ich versuche, früher aufzustehen."),
 "bedeuten": ("Verb", "Einen bestimmten Sinn haben.", "Dieses Wort bedeutet etwas anderes auf Englisch."),
 "erklären": ("Verb", "Etwas so sagen, dass andere es verstehen.", "Kannst du mir das noch einmal erklären?"),
 "zeigen": ("Verb", "Etwas sichtbar machen, damit andere es sehen.", "Er zeigt mir seine neue Wohnung."),
 "bieten": ("Verb", "Etwas anbieten, zur Verfügung stellen.", "Das Hotel bietet einen tollen Blick aufs Meer."),
 "steigen": ("Verb", "Größer, höher oder mehr werden.", "Die Preise steigen jedes Jahr ein wenig."),
 "sinken": ("Verb", "Kleiner, niedriger oder weniger werden.", "Die Temperaturen sinken im Winter stark."),
 "wachsen": ("Verb", "Größer oder mehr werden.", "Die Stadt wächst sehr schnell."),
 "verändern": ("Verb", "Anders werden oder anders machen als vorher.", "Das Internet hat unser Leben stark verändert."),
 "entscheiden": ("Verb", "Eine Wahl zwischen mehreren Möglichkeiten treffen.", "Ich kann mich nicht entscheiden, welches Kleid ich kaufe."),
 "teilnehmen": ("Verb", "Bei etwas mitmachen.", "Über vierzig Firmen haben teilgenommen."),
 "empfehlen": ("Verb", "Sagen, dass etwas gut ist und man es tun sollte.", "Ich empfehle dir dieses Restaurant."),
 "fahren": ("Verb", "Sich mit einem Fahrzeug fortbewegen.", "Wir fahren morgen mit dem Zug nach Hamburg."),
 "laufen": ("Verb", "Sich zu Fuß schnell bewegen, meistens schneller als beim normalen Gehen.", "Die Kinder laufen zur Schule."),
 "verstehen": ("Verb", "Den Sinn von etwas erfassen.", "Ich verstehe die Aufgabe nicht ganz."),
 "suchen": ("Verb", "Versuchen, etwas zu finden.", "Er sucht seinen verlorenen Schlüssel."),
 "spenden": ("Verb", "Geld oder Dinge freiwillig weggeben, um zu helfen.", "Sie spendet das Geld einer Stiftung."),
 "verlieren": ("Verb", "Etwas nicht mehr haben, ohne es absichtlich weggegeben zu haben.", "Ich habe meinen Regenschirm verloren."),
 "vergessen": ("Verb", "Sich nicht mehr an etwas erinnern.", "Ich habe seinen Namen leider vergessen."),
 "gehören": ("Verb", "Jemandem als Eigentum zugeordnet sein.", "Dieses Haus gehört meiner Familie."),
 "untersuchen": ("Verb", "Genau prüfen, wie etwas ist oder funktioniert.", "Die Ärztin untersucht den Patienten."),
 "verbringen": ("Verb", "Zeit an einem Ort oder mit einer Tätigkeit nutzen.", "Wir verbringen den Urlaub am Meer."),
 "benutzen": ("Verb", "Etwas für einen bestimmten Zweck verwenden.", "Ich benutze mein Fahrrad jeden Tag."),
 "funktionieren": ("Verb", "So arbeiten, wie es soll; richtig laufen.", "Mein Computer funktioniert nicht mehr richtig."),
 "aufräumen": ("Verb", "Dinge wieder an ihren richtigen Platz bringen; Ordnung machen.", "Am Samstag räume ich meine Wohnung auf."),
 "greifen": ("Verb", "Mit der Hand nach etwas fassen.", "Er greift in seine Tasche."),
 "öffnen": ("Verb", "Etwas aufmachen, das geschlossen war.", "Kannst du bitte das Fenster öffnen?"),
 "existieren": ("Verb", "Wirklich vorhanden sein, es geben.", "Dieses alte Gebäude existiert noch heute."),
 "wünschen": ("Verb", "Möchten, dass etwas passiert oder wahr wird.", "Ich wünsche dir alles Gute."),
 "verstecken": ("Verb", "Etwas an einen Ort legen, wo es niemand findet.", "Die Kinder verstecken sich im Garten."),
 "sammeln": ("Verb", "Mehrere Dinge nach und nach an einem Ort zusammenbringen.", "Er sammelt seit Jahren alte Briefmarken."),

 # --- Adjektive ---
 "wichtig": ("Adjektiv", "Von großer Bedeutung.", "Diese Prüfung ist sehr wichtig für mich."),
 "schwierig": ("Adjektiv", "Nicht leicht, mit Problemen verbunden.", "Die Aufgabe war schwieriger als gedacht."),
 "einfach": ("Adjektiv", "Nicht schwierig, leicht zu verstehen oder zu tun.", "Das Rezept ist ganz einfach."),
 "deutlich": ("Adjektiv", "Klar und gut zu erkennen.", "Die Preise sind deutlich gestiegen."),
 "besonders": ("Adjektiv", "Nicht gewöhnlich, anders als sonst; sehr.", "Heute war ein besonderer Tag."),
 "tatsächlich": ("Adjektiv", "In Wirklichkeit, wirklich.", "Er hat es tatsächlich geschafft."),
 "neu": ("Adjektiv", "Erst vor kurzer Zeit entstanden, gekauft oder kennengelernt.", "Ich habe ein neues Handy gekauft."),
 "alt": ("Adjektiv", "Schon lange existierend; nicht mehr jung.", "Das ist ein sehr altes Haus."),
 "groß": ("Adjektiv", "Von beträchtlicher Größe.", "Sie wohnen in einer großen Wohnung."),
 "klein": ("Adjektiv", "Nicht groß.", "Das Café ist ziemlich klein."),
 "kurz": ("Adjektiv", "Nicht lang; wenig Zeit dauernd.", "Der Film war ziemlich kurz."),
 "schnell": ("Adjektiv", "Mit hoher Geschwindigkeit.", "Er läuft sehr schnell."),
 "ruhig": ("Adjektiv", "Ohne Lärm oder Unruhe.", "Es ist heute sehr ruhig in der Stadt."),
 "gesund": ("Adjektiv", "In gutem körperlichem Zustand; nicht krank.", "Obst und Gemüse sind gesund."),
 "sicher": ("Adjektiv", "Ohne Gefahr; ganz gewiss.", "Bist du sicher, dass das stimmt?"),
 "ähnlich": ("Adjektiv", "Fast gleich, vergleichbar.", "Die beiden Häuser sehen sich sehr ähnlich."),
 "direkt": ("Adjektiv", "Ohne Umweg, unmittelbar.", "Der Zug fährt direkt nach Berlin."),
 "gefährlich": ("Adjektiv", "Mit Risiko verbunden; kann Schaden verursachen.", "Diese Straße ist bei Nacht gefährlich."),
 "freundlich": ("Adjektiv", "Nett und höflich zu anderen Menschen.", "Der Verkäufer war sehr freundlich."),
 "neugierig": ("Adjektiv", "Man möchte gern mehr über etwas wissen.", "Die Kinder sind sehr neugierig."),
 "verschieden": ("Adjektiv", "Nicht gleich; unterschiedlich.", "Die beiden Brüder sind sehr verschieden."),
 "regelmäßig": ("Adjektiv", "Immer wieder in gleichen Abständen.", "Regelmäßige Bewegung tut dem Körper gut."),
 "gewöhnlich": ("Adjektiv", "So, wie es normalerweise ist; normal.", "Es war ein ganz gewöhnlicher Tag."),
 "vertraut": ("Adjektiv", "Bekannt und angenehm, wie etwas, das man schon kennt.", "Die Straße kam ihr plötzlich vertraut vor."),
 "seltsam": ("Adjektiv", "Ungewöhnlich, komisch.", "Das war ein seltsames Gefühl."),
 "verschollen": ("Adjektiv", "Verschwunden und seit langer Zeit nicht mehr gefunden.", "Der Schatz galt lange als verschollen."),
 "wertvoll": ("Adjektiv", "Von hohem Wert; kostbar.", "Der alte Ring ist sehr wertvoll."),

 # --- Nomen / Themen ---
 "Arbeit": ("Substantiv", "Eine Tätigkeit, die man tut, oft gegen Geld.", "Meine Arbeit macht mir viel Spaß."),
 "Firma": ("Substantiv", "Ein Unternehmen, das Waren oder Dienstleistungen anbietet.", "Er arbeitet seit fünf Jahren bei dieser Firma."),
 "Unternehmen": ("Substantiv", "Eine Firma; eine Organisation, die etwas verkauft oder anbietet.", "Das Unternehmen hat viele Mitarbeiter."),
 "Modell": ("Substantiv", "Eine bestimmte Art, etwas zu organisieren oder zu erklären.", "Dieses Modell funktioniert in vielen Ländern gut."),
 "Entwicklung": ("Substantiv", "Ein Vorgang, bei dem sich etwas verändert oder verbessert.", "Die Entwicklung der Technik geht sehr schnell."),
 "Herausforderung": ("Substantiv", "Eine schwierige Aufgabe, die Mühe kostet.", "Die neue Sprache zu lernen ist eine Herausforderung."),
 "Zeit": ("Substantiv", "Die Dauer, in der etwas passiert: Stunden, Tage, Jahre.", "Ich habe heute keine Zeit."),
 "Geld": ("Substantiv", "Was man zum Bezahlen benutzt: Münzen und Scheine.", "Ich habe nicht genug Geld dabei."),
 "Gefühl": ("Substantiv", "Ein innerer Zustand wie Freude, Angst oder Trauer.", "Sie hatte ein gutes Gefühl bei der Entscheidung."),
 "Glück": ("Substantiv", "Ein gutes Gefühl, wenn alles gut läuft, oder ein günstiger Zufall.", "Zum Glück hatten wir noch genug Zeit."),
 "Problem": ("Substantiv", "Eine Schwierigkeit, die gelöst werden muss.", "Wir haben ein kleines Problem mit dem Computer."),
 "Lösung": ("Substantiv", "Eine Antwort auf ein Problem.", "Er hat eine gute Lösung für das Problem gefunden."),
 "Beispiel": ("Substantiv", "Ein Fall, der etwas Allgemeines zeigt.", "Kannst du mir ein Beispiel geben?"),
 "Grund": ("Substantiv", "Die Ursache, warum etwas passiert.", "Aus welchem Grund bist du zu spät gekommen?"),
 "Idee": ("Substantiv", "Ein neuer Gedanke.", "Das ist eine gute Idee!"),
 "Frage": ("Substantiv", "Was man sagt, wenn man etwas wissen möchte.", "Ich habe noch eine Frage."),
 "Antwort": ("Substantiv", "Was man sagt, um auf eine Frage zu reagieren.", "Das war eine ehrliche Antwort."),
 "Nachricht": ("Substantiv", "Eine Information, die man jemandem mitteilt.", "Ich habe eine wichtige Nachricht für dich."),
 "Geschichte": ("Substantiv", "Eine Erzählung von Ereignissen, echt oder erfunden.", "Er erzählt eine spannende Geschichte."),
 "Erinnerung": ("Substantiv", "Ein Gedanke an etwas aus der Vergangenheit.", "Das Foto ist eine schöne Erinnerung."),
 "Brief": ("Substantiv", "Ein Text auf Papier, den man jemandem schickt.", "Sie hat einen langen Brief geschrieben."),
 "Postkarte": ("Substantiv", "Eine kleine Karte mit Bild, die man ohne Umschlag verschickt.", "Ich schicke dir eine Postkarte aus dem Urlaub."),
 "Foto": ("Substantiv", "Ein Bild, das mit einer Kamera gemacht wurde.", "Kannst du ein Foto von uns machen?"),
 "Schlüssel": ("Substantiv", "Ein kleines Metallstück, mit dem man eine Tür öffnet.", "Ich habe meinen Schlüssel verloren."),
 "Adresse": ("Substantiv", "Die genaue Angabe, wo jemand wohnt.", "Kannst du mir deine Adresse geben?"),
 "Reise": ("Substantiv", "Eine Fahrt zu einem anderen Ort.", "Die Reise nach Spanien war wunderschön."),
 "Zug": ("Substantiv", "Ein Fahrzeug auf Schienen, das viele Menschen transportiert.", "Der Zug fährt in zehn Minuten ab."),
 "Schatz": ("Substantiv", "Etwas sehr Wertvolles, oft versteckt oder aus alter Zeit.", "Die Kinder suchten einen versteckten Schatz."),
 "Stiftung": ("Substantiv", "Eine Organisation, die Geld für einen guten Zweck sammelt und einsetzt.", "Sie spendet regelmäßig an eine Stiftung."),
 "Kündigung": ("Substantiv", "Das Ende eines Arbeitsvertrags.", "Die Zahl der Kündigungen ist gesunken."),
 "Homeoffice": ("Substantiv", "Wenn man von zu Hause aus arbeitet statt im Büro.", "Sie arbeitet zwei Tage pro Woche im Homeoffice."),

 # --- Natur / gesellschaftliche Themen ---
 "Wal": ("Substantiv", "Ein sehr großes Tier, das im Meer lebt.", "Vor der Küste wurde ein Wal gesichtet."),
 "Fisch": ("Substantiv", "Ein Tier, das im Wasser lebt und schwimmt.", "Im See gibt es viele Fische."),
 "Umwelt": ("Substantiv", "Die Natur um uns herum: Luft, Wasser, Pflanzen, Tiere.", "Wir sollten die Umwelt besser schützen."),
 "Klimawandel": ("Substantiv", "Die langfristige Veränderung des Wetters auf der Erde.", "Der Klimawandel betrifft die ganze Welt."),
 "Energie": ("Substantiv", "Die Kraft, die man braucht, damit etwas funktioniert, z. B. Strom.", "Windräder erzeugen saubere Energie."),
 "Gesundheit": ("Substantiv", "Der Zustand, gesund zu sein.", "Sport ist gut für die Gesundheit."),
 "Natur": ("Substantiv", "Alles, was nicht von Menschen gemacht wurde: Bäume, Tiere, Berge.", "Im Urlaub genießen wir die Natur."),
 "Meer": ("Substantiv", "Eine sehr große Menge Salzwasser.", "Wir schwimmen gern im Meer."),
 "Wetter": ("Substantiv", "Wie es draußen ist: Sonne, Regen, Wind, Temperatur.", "Das Wetter ist heute sehr schön."),
 "Regen": ("Substantiv", "Wasser, das vom Himmel fällt.", "Nimm einen Schirm mit, es gibt Regen."),
 "Sturm": ("Substantiv", "Sehr starker Wind, oft mit Regen.", "Nach dem Sturm lagen Äste auf der Straße."),
 "Nachhaltigkeit": ("Substantiv", "Etwas so machen, dass es der Umwelt und der Zukunft nicht schadet.", "Viele Firmen achten heute auf Nachhaltigkeit."),
 "Digitalisierung": ("Substantiv", "Wenn immer mehr mit Computern und dem Internet gemacht wird.", "Die Digitalisierung verändert viele Berufe."),
 "Prozent": ("Substantiv", "Ein Teil von hundert; Zeichen %.", "Fast fünfzig Prozent stimmten dafür."),
 "Anzahl": ("Substantiv", "Wie viele von etwas es gibt.", "Die Anzahl der Besucher ist gestiegen."),
 "Bootstour": ("Substantiv", "Eine organisierte Fahrt mit einem Boot, oft für Touristen.", "Die Bootstour dauert etwa zwei Stunden."),
 "Termin": ("Substantiv", "Ein festgelegter Zeitpunkt für ein Treffen.", "Ich habe morgen einen Termin beim Arzt."),
}

# surface form (as it appears in the app's own text, lowercase) -> lemma key above
FORMS = {
 "jahr":"Jahr","jahre":"Jahr","jahren":"Jahr","jahres":"Jahr",
 "woche":"Woche","wochen":"Woche",
 "tag":"Tag","tage":"Tag","tagen":"Tag","tages":"Tag",
 "monat":"Monat","monate":"Monat","monaten":"Monat",
 "abend":"Abend","abends":"Abend",
 "wochenende":"Wochenende","wochenenden":"Wochenende",
 "heute":"heute",
 "damals":"damals",
 "letzte":"letzte","letzten":"letzte","letzter":"letzte","letztes":"letzte",
 "nächste":"nächste","nächsten":"nächste","nächster":"nächste","nächstes":"nächste",
 "inzwischen":"inzwischen",
 "plötzlich":"plötzlich",
 "endlich":"endlich",
 "früher":"früher",
 "erst":"erst",

 "familie":"Familie",
 "vater":"Vater","vaters":"Vater",
 "mutter":"Mutter",
 "großvater":"Großvater","großvaters":"Großvater",
 "großmutter":"Großmutter",
 "bruder":"Bruder","brüder":"Bruder",
 "schwester":"Schwester",
 "kind":"Kind","kinder":"Kind","kindes":"Kind","kindern":"Kind",
 "eltern":"Eltern",
 "ehepaar":"Ehepaar",

 "mensch":"Mensch","menschen":"Mensch",
 "frau":"Frau","frauen":"Frau",
 "mann":"Mann","männer":"Mann",
 "angestellte":"Angestellte","angestellter":"Angestellte","angestellten":"Angestellte",
 "experte":"Experte","experten":"Experte","expertin":"Experte",
 "forscher":"Forscher","forschern":"Forscher","forscherin":"Forscher",
 "nachbarin":"Nachbarin","nachbar":"Nachbarin","nachbarn":"Nachbarin",
 "mitarbeiter":"Mitarbeiter","mitarbeitern":"Mitarbeiter",
 "chef":"Chef","chefin":"Chef",
 "rentnerin":"Rentnerin","rentner":"Rentnerin",

 "stadt":"Stadt","städte":"Stadt","städten":"Stadt",
 "dorf":"Dorf",
 "bank":"Bank","bankgebäude":"Bank",
 "bahnhof":"Bahnhof",
 "insel":"Insel",
 "küste":"Küste","küstenstädte":"Küste",
 "dachboden":"Dachboden",
 "ferienhaus":"Ferienhaus",

 "arbeiten":"arbeiten","arbeitet":"arbeiten","arbeitete":"arbeiten",
 "finden":"finden","findet":"finden","fand":"finden","gefunden":"finden",
 "bringen":"bringen","bringt":"bringen","brachte":"bringen",
 "bleiben":"bleiben","bleibt":"bleiben","blieb":"bleiben",
 "brauchen":"brauchen","braucht":"brauchen","brauchte":"brauchen",
 "glauben":"glauben","glaubt":"glauben","glaubte":"glauben",
 "erinnert":"erinnern","erinnern":"erinnern","erinnerte":"erinnern",
 "erzählen":"erzählen","erzählt":"erzählen","erzählte":"erzählen",
 "beschließen":"beschließen","beschließt":"beschließen","beschlossen":"beschließen",
 "versuchen":"versuchen","versucht":"versuchen","versuchte":"versuchen",
 "bedeuten":"bedeuten","bedeutet":"bedeuten",
 "erklären":"erklären","erklärt":"erklären","erklärte":"erklären",
 "zeigen":"zeigen","zeigt":"zeigen","zeigte":"zeigen",
 "bieten":"bieten","bietet":"bieten","bot":"bieten",
 "steigen":"steigen","steigt":"steigen","gestiegen":"steigen",
 "sinken":"sinken","sinkt":"sinken","gesunken":"sinken",
 "wachsen":"wachsen","wächst":"wachsen","gewachsen":"wachsen",
 "verändern":"verändern","verändert":"verändern","veränderte":"verändern",
 "entscheiden":"entscheiden","entscheidet":"entscheiden","entschieden":"entscheiden",
 "teilnehmen":"teilnehmen","teilgenommen":"teilnehmen","nimmt":"teilnehmen",
 "empfehlen":"empfehlen","empfiehlt":"empfehlen","empfehlung":"empfehlen",
 "fahren":"fahren","fährt":"fahren","fuhr":"fahren",
 "laufen":"laufen","läuft":"laufen","lief":"laufen","gelaufen":"laufen",
 "verstehen":"verstehen","versteht":"verstehen","verstand":"verstehen",
 "suchen":"suchen","sucht":"suchen","suchte":"suchen",
 "spenden":"spenden","spendet":"spenden",
 "verlieren":"verlieren","verliert":"verlieren","verloren":"verlieren",
 "vergessen":"vergessen","vergisst":"vergessen","vergaß":"vergessen",
 "gehören":"gehören","gehört":"gehören","gehörte":"gehören",
 "untersuchen":"untersuchen","untersucht":"untersuchen",
 "verbringen":"verbringen","verbringt":"verbringen","verbrachte":"verbringen",
 "benutzen":"benutzen","benutzt":"benutzen",
 "funktionieren":"funktionieren","funktioniert":"funktionieren",
 "aufräumen":"aufräumen","räumt":"aufräumen","aufgeräumt":"aufräumen",
 "greift":"greifen","greifen":"greifen",
 "öffnen":"öffnen","öffnet":"öffnen",
 "existieren":"existieren","existiert":"existieren",
 "wünschen":"wünschen","wünschte":"wünschen","gewünscht":"wünschen",
 "verstecken":"verstecken","versteckt":"verstecken","versteckte":"verstecken",
 "sammeln":"sammeln","sammelt":"sammeln","gesammelt":"sammeln",

 "wichtig":"wichtig","wichtiger":"wichtig","wichtigsten":"wichtig",
 "schwierig":"schwierig","schwieriger":"schwierig",
 "einfach":"einfach",
 "deutlich":"deutlich",
 "besonders":"besonders","besondere":"besonders","besonderer":"besonders",
 "tatsächlich":"tatsächlich",
 "neu":"neu","neue":"neu","neuen":"neu","neues":"neu","neuer":"neu",
 "alt":"alt","alte":"alt","alten":"alt","älter":"alt","ältere":"alt",
 "groß":"groß","große":"groß","großen":"groß","größte":"groß",
 "klein":"klein","kleine":"klein","kleinen":"klein",
 "kurz":"kurz","kurzer":"kurz","kürzere":"kurz",
 "schnell":"schnell","schnelle":"schnell","schneller":"schnell",
 "ruhig":"ruhig","ruhige":"ruhig","ruhigen":"ruhig",
 "gesund":"gesund","gesunde":"gesund",
 "sicher":"sicher","sichere":"sicher",
 "ähnlich":"ähnlich","ähnlichkeiten":"ähnlich",
 "direkt":"direkt",
 "gefährlich":"gefährlich","gefährliche":"gefährlich",
 "freundlich":"freundlich","freundlicher":"freundlich",
 "neugierig":"neugierig",
 "verschieden":"verschieden",
 "regelmäßig":"regelmäßig","regelmäßige":"regelmäßig",
 "gewöhnlich":"gewöhnlich",
 "vertraut":"vertraut",
 "seltsam":"seltsam","seltsame":"seltsam","seltsames":"seltsam",
 "verschollen":"verschollen","verschollenen":"verschollen",
 "wertvoll":"wertvoll","wertvolle":"wertvoll",

 "arbeit":"Arbeit",
 "firma":"Firma","firmen":"Firma",
 "unternehmen":"Unternehmen",
 "modell":"Modell",
 "entwicklung":"Entwicklung",
 "herausforderung":"Herausforderung","herausforderungen":"Herausforderung",
 "zeit":"Zeit",
 "geld":"Geld",
 "gefühl":"Gefühl",
 "glück":"Glück",
 "problem":"Problem","probleme":"Problem",
 "lösung":"Lösung","lösungen":"Lösung",
 "beispiel":"Beispiel","beispiele":"Beispiel","beispielsweise":"Beispiel",
 "grund":"Grund","gründe":"Grund",
 "idee":"Idee","ideen":"Idee",
 "frage":"Frage","fragen":"Frage","fragt":"Frage",
 "antwort":"Antwort","antworten":"Antwort",
 "nachricht":"Nachricht","nachrichten":"Nachricht",
 "geschichte":"Geschichte","geschichten":"Geschichte",
 "erinnerung":"Erinnerung","erinnerungen":"Erinnerung",
 "brief":"Brief","briefe":"Brief",
 "postkarte":"Postkarte","postkarten":"Postkarte",
 "foto":"Foto","fotos":"Foto",
 "schlüssel":"Schlüssel",
 "adresse":"Adresse",
 "reise":"Reise","reisen":"Reise",
 "zug":"Zug","züge":"Zug",
 "schatz":"Schatz",
 "stiftung":"Stiftung",
 "kündigung":"Kündigung","kündigungen":"Kündigung",
 "homeoffice":"Homeoffice",

 "wal":"Wal","wale":"Wal","walen":"Wal","walart":"Wal",
 "fisch":"Fisch","fische":"Fisch","fischen":"Fisch",
 "umwelt":"Umwelt",
 "klimawandel":"Klimawandel",
 "energie":"Energie",
 "gesundheit":"Gesundheit",
 "natur":"Natur",
 "meer":"Meer","meere":"Meer","meeres":"Meer",
 "wetter":"Wetter",
 "regen":"Regen",
 "sturm":"Sturm",
 "nachhaltigkeit":"Nachhaltigkeit",
 "digitalisierung":"Digitalisierung",
 "prozent":"Prozent",
 "anzahl":"Anzahl",
 "bootstour":"Bootstour","bootstouren":"Bootstour",
 "termin":"Termin","termine":"Termin",
}
